equipInfo = [
    {
        name: '埃力格',
        part: '左五',
        set: '',
        allSkillDmg: 5,
        atk: 3,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '童話',
        part: '左五',
        set: '',
        allSkillDmg: 3,
        atk: 0,
        critDmg: 0,
        polar: 7,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '童話武器',
        part: '武器',
        set: '童話',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '童話上衣',
        part: '上衣',
        set: '童話',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '童話手臂',
        part: '手臂',
        set: '童話',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '童話耳環',
        part: '耳環',
        set: '童話',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '極光',
        part: '左五',
        set: '',
        allSkillDmg: 2,
        atk: 3,
        critDmg: 0,
        polar: 5,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '極光武器',
        part: '武器',
        set: '極光',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 5,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '極光上衣',
        part: '上衣',
        set: '極光',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '極光項鍊',
        part: '項鍊',
        set: '極光',
        allSkillDmg: 0,
        atk: 1,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '使徒',
        part: '左五',
        set: '',
        allSkillDmg: 0,
        atk: 4,
        critDmg: 0,
        polar: 6,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '使徒武器',
        part: '武器',
        set: '使徒',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '使徒上衣',
        part: '上衣',
        set: '使徒',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '使徒耳環',
        part: '耳環',
        set: '使徒',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '滄海',
        part: '左五',
        set: '',
        allSkillDmg: 0,
        atk: 4,
        critDmg: 0,
        polar: 4,
        bossDmg: 0,
        adapt: 2,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '滄海武器',
        part: '武器',
        set: '滄海',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 3,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '滄海支援',
        part: '支援',
        set: '滄海',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '滄海上衣',
        part: '上衣',
        set: '滄海',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '滄海下衣',
        part: '下衣',
        set: '滄海',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '神聖騎士',
        part: '左五',
        set: '',
        allSkillDmg: 4,
        atk: 0,
        critDmg: 0,
        polar: 2,
        bossDmg: 0,
        adapt: 5,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '聖騎武器',
        part: '武器',
        set: '聖騎',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 5,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '聖騎支援',
        part: '支援',
        set: '聖騎',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '聖騎上衣',
        part: '上衣',
        set: '聖騎',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '聖騎下衣',
        part: '下衣',
        set: '聖騎',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '薔薇魔法',
        part: '左五',
        set: '',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 5,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '薔薇武器',
        part: '武器',
        set: '薔薇',
        allSkillDmg: 5,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '薔薇支援',
        part: '支援',
        set: '薔薇',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '薔薇臉下',
        part: '臉下',
        set: '薔薇',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 1,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '薔薇上衣',
        part: '上衣',
        set: '薔薇',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 1,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '122花冠',
        part: '頭上',
        set: '',
        allSkillDmg: 0,
        atk: -5,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '156皇冠',
        part: '頭上',
        set: '',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 2,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '12R武飾',
        part: '武飾',
        set: '12R',
        allSkillDmg: 10,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '18R武飾',
        part: '武飾',
        set: '18R',
        allSkillDmg: 15,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '18R支援',
        part: '支援',
        set: '18R',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 3,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '18R下衣',
        part: '下衣',
        set: '18R',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '魔族之眼',
        part: '支援',
        set: '12R',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 5,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '163支援',
        part: '支援',
        set: '',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 5,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '大師臉中',
        part: '臉中',
        set: '大師',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '162臉中',
        part: '臉中',
        set: '',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 2,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '不息之火',
        part: '下衣',
        set: '12R',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '175下衣',
        part: '下衣',
        set: '',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 2,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '大師手臂',
        part: '手臂',
        set: '大師',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 1,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '174手臂',
        part: '手臂',
        set: '',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 1,
        bossDmg: 0,
        adapt: 2,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '大師耳環',
        part: '耳環',
        set: '大師',
        allSkillDmg: 1,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '155耳環',
        part: '耳環',
        set: '',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 3,
        polar: 0,
        bossDmg: 0,
        adapt: 2,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '3攻項鍊',
        part: '項鍊',
        set: '',
        allSkillDmg: 0,
        atk: 3,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '大師項鍊',
        part: '項鍊',
        set: '大師',
        allSkillDmg: 0,
        atk: 0.5,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '4攻',
        part: '聖獸戒指',
        set: '',
        allSkillDmg: 0,
        atk: 4,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '4兩極',
        part: '聖獸戒指',
        set: '',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 4,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '2攻2兩極',
        part: '聖獸戒指',
        set: '',
        allSkillDmg: 0,
        atk: 2,
        critDmg: 0,
        polar: 2,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    }
]