setInfo = [
    {
        name: '童話右二',
        setKey: '童話',
        count: '2',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 5,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '童話右三',
        setKey: '童話',
        count: '3',
        allSkillDmg: 2,
        atk: 3,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '極光右二',
        setKey: '極光',
        count: '2',
        allSkillDmg: 0,
        atk: 3,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '極光右三',
        setKey: '極光',
        count: '3',
        allSkillDmg: 8,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '使徒右二',
        setKey: '使徒',
        count: '2',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 4,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '使徒右三',
        setKey: '使徒',
        count: '3',
        allSkillDmg: 5,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '滄海右二',
        setKey: '滄海',
        count: '2',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 3,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '滄海右三',
        setKey: '滄海',
        count: '3',
        allSkillDmg: 8,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '聖騎右二',
        setKey: '聖騎',
        count: '2',
        allSkillDmg: 3,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '聖騎右三',
        setKey: '聖騎',
        count: '3',
        allSkillDmg: 2,
        atk: 0,
        critDmg: 0,
        polar: 5,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '薔薇右二',
        setKey: '薔薇',
        count: '2',
        allSkillDmg: 0,
        atk: 3,
        critDmg: 2,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '薔薇右三',
        setKey: '薔薇',
        count: '3',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 5,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '人形右二',
        setKey: '人形',
        count: '2',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 3,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '人形右三',
        setKey: '人形',
        count: '3',
        allSkillDmg: 2,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 5,
        cooldown: 0
    },
    {
        name: '暗夜右二',
        setKey: '暗夜',
        count: '2',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 3,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '暗夜右三',
        setKey: '暗夜',
        count: '3',
        allSkillDmg: 2,
        atk: 5,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '乙太右二',
        setKey: '乙太',
        count: '2',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 5,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '乙太右三',
        setKey: '乙太',
        count: '3',
        allSkillDmg: 3,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 3,
        cooldown: 0
    },
    {
        name: '羅索飾品二',
        setKey: '12R',
        count: '2',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 5,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '羅索飾品三',
        setKey: '12R',
        count: '3',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 5,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '大師二',
        setKey: '大師',
        count: '2',
        allSkillDmg: 0,
        atk: 3,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 1,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '大師三',
        setKey: '大師',
        count: '3',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 3,
        bossDmg: 0,
        adapt: 2,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '深淵飾品二',
        setKey: '18R',
        count: '2',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 5,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '深淵飾品三',
        setKey: '18R',
        count: '3',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 3,
        bossDmg: 0,
        adapt: 0,
        bleed: 3,
        cooldown: 0
    }
]