unreleaseEquipInfo = [
    {
        name: '自動人形',
        setKey: '左五',
        count: '',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 5,
        bossDmg: 0,
        adapt: 3,
        bleed: 2,
        cooldown: 0
    },
    {
        name: '人形武器',
        setKey: '武器',
        count: '人形',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 5,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '人形臉下',
        setKey: '臉下',
        count: '人形',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '人形上衣',
        setKey: '上衣',
        count: '人形',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '人形下衣',
        setKey: '下衣',
        count: '人形',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '人形項鍊',
        setKey: '項鍊',
        count: '人形',
        allSkillDmg: 0,
        atk: 1,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '暗夜獵手',
        setKey: '左五',
        count: '',
        allSkillDmg: 2,
        atk: 0,
        critDmg: 0,
        polar: 8,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '暗夜武器',
        setKey: '武器',
        count: '暗夜',
        allSkillDmg: 2,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 3,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '暗夜支援',
        setKey: '支援',
        count: '暗夜',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '暗夜上衣',
        setKey: '上衣',
        count: '暗夜',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '暗夜手臂',
        setKey: '手臂',
        count: '暗夜',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '乙太貴族',
        setKey: '左五',
        count: '',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 5,
        bossDmg: 0,
        adapt: 0,
        bleed: 5,
        cooldown: 0
    },
    {
        name: '乙太武器',
        setKey: '武器',
        count: '乙太',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 5,
        cooldown: 0
    },
    {
        name: '乙太耳環',
        setKey: '耳環',
        count: '乙太',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '乙太上衣',
        setKey: '上衣',
        count: '乙太',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '乙太下衣',
        setKey: '下衣',
        count: '乙太',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    }
]