unreleaseEquipInfo = [
    {
        name: '強者排熱',
        part: '上衣',
        set: '',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '暗夜獵手',
        part: '左五',
        set: '',
        allSkillDmg: 2,
        atk: 0,
        critDmg: 0,
        polar: 8,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '暗夜武器',
        part: '武器',
        set: '暗夜',
        allSkillDmg: 2,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 3,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '暗夜支援',
        part: '支援',
        set: '暗夜',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '暗夜上衣',
        part: '上衣',
        set: '暗夜',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '暗夜手臂',
        part: '手臂',
        set: '暗夜',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '乙太貴族',
        part: '左五',
        set: '',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 5,
        bossDmg: 0,
        adapt: 0,
        bleed: 5,
        cooldown: 0
    },
    {
        name: '乙太武器',
        part: '武器',
        set: '乙太',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 5,
        cooldown: 0
    },
    {
        name: '乙太耳環',
        part: '耳環',
        set: '乙太',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    },
    {
        name: '乙太上衣',
        part: '上衣',
        set: '乙太',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 5
    },
    {
        name: '乙太下衣',
        part: '下衣',
        set: '乙太',
        allSkillDmg: 0,
        atk: 0,
        critDmg: 0,
        polar: 0,
        bossDmg: 0,
        adapt: 0,
        bleed: 0,
        cooldown: 0
    }
]